---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:

          - id: black
            name: Format with Black
            entry: conda run -n neara-buildbot poetry run black
            language: system
            types: [python]

          - id: ruff
            name: Check with Ruff
            entry: conda run -n neara-buildbot poetry run ruff
            language: system
            pass_filenames: false
            always_run: true
            args: ["check", "buildbot", "tests", "--fix"]

          - id: mypy
            name: Validate types with MyPy
            entry: conda run -n neara-buildbot poetry run mypy
            language: system
            types: [python]
            pass_filenames: false
            args:
              - "buildbot"
