services:
  api:
    build: &build
      context: .
      dockerfile: ./Dockerfile
    image: &image buildbot:${BUILDBOT_VERSION:-latest}
    restart: &restart always
    env_file: &env_file
      - .env
    networks:
      - front-end-network
      - back-end-network
    ports:
      - 8000:8000
    volumes:
      - buildbot_data:/app/data:ro

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - back-end-network

  taskiq-worker:
    build: *build
    image: *image
    restart: *restart
    env_file: *env_file
    volumes:
      - buildbot_data:/app/data:rw
    networks:
      - back-end-network
    command:
      - taskiq
      - worker
      - app.background:broker

volumes:
  buildbot_data:
    driver: local

networks:
  front-end-network:
    driver: bridge
  back-end-network:
    driver: bridge
