networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  storage:
    driver: local
  certs:

services:
  api:
    container_name: api
    build: &build
      context: .
      dockerfile: ./Dockerfile
    image: &image buildbot:${BUILDBOT_VERSION:-latest}
    restart: &restart unless-stopped
    env_file: &env_file
      - .env
    networks:
      - frontend
      - &backend_net backend
    ports:
      - 8000:8000
    environment: &docker_env
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - storage:/app/buildbot/data:ro
      - &certs certs:/certs
    depends_on:
      - redis
      - docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  job-manager:
    container_name: job-manager
    build: *build
    image: *image
    restart: *restart
    env_file: *env_file
    environment: *docker_env
    volumes:
      - &rw_storage storage:/app/buildbot/data:rw
      - *certs
    networks:
      - *backend_net
    command:
      - taskiq
      - scheduler
      - app.background.broker:scheduler
    depends_on:
      - redis
      - docker

  redis:
    image: redis
    networks:
      - *backend_net

  docker:
    image: docker:dind
    privileged: yes
    restart: *restart
    container_name: docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - *backend_net
    volumes:
      - *rw_storage
      - *certs
