services:
  api:
    container_name: api
    build: &build
      context: .
      dockerfile: ./Dockerfile
    image: &image buildbot:${BUILDBOT_VERSION:-latest}
    restart: &restart always
    env_file: &env_file
      - .env
    networks:
      - backend
    ports:
      - 8000:8000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - storage:/app/buildbot/data:ro
      - certs:/certs
    depends_on:
      - redis
      - docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  job-manager:
    container_name: job-manager
    build: *build
    image: *image
    restart: *restart
    env_file: *env_file
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - storage:/app/buildbot/data:rw
      - certs:/certs
    networks:
      - backend
    command:
      - taskiq
      - scheduler
      - app.background.broker:scheduler
    depends_on:
      - redis
      - docker

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend

  docker:
    image: docker:dind
    privileged: yes
    restart: unless-stopped
    container_name: docker
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - backend
    volumes:
      - storage:/app/buildbot/data:rw
      - certs:/certs

volumes:
  storage:
    driver: local
  certs:

networks:
  backend:
    driver: bridge
