version: "3.8"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  storage:
    driver: local

services:
  api:
    container_name: api
    build: &build
      context: .
      dockerfile: ./Dockerfile
    image: &image buildbot:${BUILDBOT_VERSION:-latest}
    restart: &restart unless-stopped
    env_file: &env_file
      - .env
    networks:
      - frontend
      - &backend_net backend
    ports:
      - 8000:8000
    volumes:
      - storage:/app/buildbot/data:ro
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  job-manager:
    container_name: job-manager
    build: *build
    image: *image
    restart: *restart
    env_file: *env_file
    volumes:
      - storage:/app/buildbot/data:rw
    networks:
      - *backend_net
    command:
      - taskiq
      - scheduler
      - app.background.broker:scheduler
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - *backend_net
